[colors]
draw_bold_text_with_bright_colors = false

[colors.bright]
white = "#42464D"
blue = "#98C1FF"
cyan = "#7AB0AF"
green = "#AEDA97"
magenta = "#D3A1EC"
red = "#FF787E"
black = "#D4D4D4"
yellow = "#FFCE79"

[colors.cursor]
cursor = "#6EA0F9"
text = "CellBackground"

[colors.normal]
white = "#959595"
blue = "#6EA0F9"
cyan = "#4D9393"
green = "#88BD69"
magenta = "#B97AD7"
red = "#F93D53"
black = "#D4D4D4"
yellow = "#FFA829"

[colors.primary]
background = "#282C34"
foreground = "#B4B4B4"

[colors.selection]
background = "#42464D"
text = "CellForeground"

[env]
TERM = "xterm-256color"

[font]
size = 12.0

[font.bold]
family = "JuliaMono"
style = "ExtraBold"

[font.bold_italic]
family = "JuliaMono"
style = "Bold Italic"

[font.italic]
family = "JuliaMono"
style = "Italic"

[font.normal]
family = "JuliaMono"
style = "Regular"

[font.offset]
x = 0
y = 1

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "PasteSelection"
key = "Insert"
mods = "Shift"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"
mods = "None"

[[keyboard.bindings]]
action = "Paste"
key = "Paste"
mods = "None"

[[keyboard.bindings]]
action = "Copy"
key = "Copy"
mods = "None"

[[keyboard.bindings]]
action = "ClearLogNotice"
key = "L"
mods = "Control"

[[keyboard.bindings]]
chars = "\f"
key = "L"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "PageUp"
mode = "~Alt"
mods = "None"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "PageDown"
mode = "~Alt"
mods = "None"

[[keyboard.bindings]]
action = "ScrollToTop"
key = "Home"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollToBottom"
key = "End"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u0017"
key = "Back"
mods = "Control"

[scrolling]
history = 100000

[terminal.shell]
args = ["-c", "(fastfetch); exec fish"]
program = "/bin/bash"

[window]
dynamic_padding = false
title = "Alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 6
y = 6

[terminal]
